name: Daily Timeform Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Download today_urls.txt
        run: |
          curl -O https://raw.githubusercontent.com/TamB10/timeform-scraper/main/today_urls.txt

      - name: Run runner scraper
        run: python github_scrape_runners.py

      - name: Commit runners.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add runners.json
          git commit -m "Scraped runners.json for $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
