name: Daily Timeform Scraper

on:
  workflow_dispatch:  # manual run button
  schedule:
    - cron: '0 5 * * *'  # runs daily at 5am UTC

    permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run scraper
      run: python scrape_timeform.py

    - name: Commit and push results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add today.json
        git commit -m "Daily scrape $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
        git push
